default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: mateuszkantyka
  password:
  host: localhost

development:
  <<: *default
  database: recruitment_web_app

test:
  <<: *default
  database: test_recruitment_web_app
